### PR TITLE
Initial support for multiple (nested) Tabs and internal links

### PR DESCRIPTION
**Pull request by holtkamp**
This PR provides initial support for sticky Tabs when multiple (nested) Tabs are involved, or an internal link is used (browse to a specific element). 

When using Tabs, it might occur that:
- an internal link within the Tab content is referred, for example as part of Tab X, section Y: 
  - www.domain.ext#tabXThatUsesHref&sectionY
  - www.domain.ext#[tabXThatUsesDataTarget]&sectionY
- nested Tabs are involved:
  - www.domain.ext#[tabXThatUsesDataTarget]&[nestedTabThatUsesDataTarget]
  - www.domain.ext#[tabXThatUsesDataTarget]&[nestedTabThatUsesDataTarget]&specificElementId

For example in an e-commerce site, one can image a permanentlink to a specific ArticleId, that is part of Catalog Z, part of Service Y, provided by supplier X:
- www.e-commerce.ext#[supplierTabX]&[serviceTabY]&[catalogTabZ]&articleId

The basic approach is to separate each of the URI fragments by a separator (defaulting to &, the ampersand), and iterate over all fragments to have the browser navigate down the path.

### CODE REVIEW

**Comment by aidanlister** [comment]
This is great, thanks.

**Comment by holtkamp** [comment]
Thanks, the reason why the `window.location.hash` is not updated while traversing down the provided 'path', is to prevent the browser address bar from changing. Users typically copy-paste URLs from the address bar to send to friends / place on Facebook, etc. 

I am not so happy with the testing approach though, got little experience with automated (regression) testing in Javascript, so I used a simple HTML based test... Someone more experienced to add tests? Any suggestions on how to tackle this?

**Comment by aidanlister** [comment]
Yeah, I don't know much about testing in JS either. I'll leave the PR open for a bit to get some community feedback. I'm a little worried we're adding too much complexity to something that was meant to be really simple but I've needed nested tabs several times so give me some time to play with it and I'll let you know.

**Comment by holtkamp** [comment]
Hi @aidanlister, I am cleaning up my GitHub repos and encountered this PR, did you have any time to have a look at it? Maybe we can tag a new major version after merge (`2.0.0-alpha`?), so current users won't be affected by potential regressions.

**Comment by holtkamp** [comment]
@aidanlister, shameless bump on this 😄

**Comment by aidanlister** [comment]
Hey @holtkamp, I like the goal but I don't want to add too much complexity to the project for a slightly less common use case. I'd merge it in if it was jquery.stickytabs-multi.js or something.

**Comment by holtkamp** [comment]
Fair point... unfortunately my JavaScript skills are not great. So I will have to research the options on how to have `jquery.stickytabs-multi.js` 'extend' the functionality of `jquery.stickytabs.js` . So lets keep this open for a bit more and I'll try to find some time this year.

**Comment by aidanlister** [comment]
I'd just duplicate it into a separate file

**Comment by holtkamp** [comment]
Ok, ["it has been a long time" => let's try again](https://www.youtube.com/watch?v=JwKQ5fHCGHo). 

As suggested in https://github.com/aidanlister/jquery-stickytabs/pull/19#issuecomment-242913278 I separated the functionality in a dedicated file. 

The GitHub GUI should allow to squash all the commits and merge it if you agree with this approach.

**Comment by holtkamp** [comment]
Minor bump on this?

**Comment by holtkamp** [comment]
@aidanlister rebased my PR, could you consider a merge?

**Comment by interludic** [comment]
Hey Mate, why not create a new repo i dont this guy wants to change?

**Comment by interludic** [comment]
So how do we get it to work?

I have the url as http://613.test/league#registration&individual
registration opens, but the second tab does not?

**Comment by aidanlister** [comment]
Sorry for delay - merged.

**Comment by holtkamp** [comment]
Thanks for merging eventually @aidanlister, could you consider tag a new release so we do not need to rely on "dev-master" to be able to use the merged functionality?

**Comment by interludic** [comment]
how does it work?

Also the master branch does not look updated

**Comment by holtkamp** [comment]
@interludic 

>how does it work?

You can have a look at the source of these tests: https://github.com/aidanlister/jquery-stickytabs/tree/master/tests

>Also the master branch does not look updated

Indeed, not recently, the PR is quite old (2 years) and was only merged recently (dec 2019)

**Comment by movethathoof** [comment]
I realize that is has been many years since this thread was active, but I've been looking for exactly this functionality and I am so pleased to have found this.

However, though I got the forward/back functionality to work (with nested tabs, what I couldn't find another means to do anywhere else), the urls come out "#[data-section='essays']&[data-section='issue2']", where the 'data-section' from the href remains. Using the plain stickytabs.js it's just the clean href that appears in the url. Is that intentional? Is there any way to generate a more usable URL?

**Comment by movethathoof** [comment]
In case anyone ever comes across this and faces the same quandary I did, this is what I came up with:

https://stackoverflow.com/questions/79443078/back-button-navigation-with-nested-tabs-using-altered-jquery-stickytabs

**Comment by holtkamp** [comment]
@movethathoof maybe you can submit a pull request? Never realized there was a bug in it when navigating back / forth....

**Comment by movethathoof** [comment]
I don't know if it's really a bug! That would depend on your intentions. It functions perfectly fine, regarding the navigation back and forth. What I wanted (and appeared to achieve with my edits) were simpler URLs. 

As I mentioned above, using the code here they came out "/#[data-section='essays']&[data-section='issue2']", where the 'data-section' from the href remains (as opposed to the plain stickytabs.js, which just gives the clean href without 'data-section' etc). So, it works, and I can't say whether that was as you intended it to.

Because I'm completely untrained with any of this, looking to use it for a bespoke personal website, I don't have the faith in my code to think that I've properly solved it haha, if there's anything to solve, since it did work before, and with my code it appears to continue to work, just more in the way I was looking for (and that perhaps others might want as well, hence my sharing it here).

**Pull request merged**
